### PR TITLE
Improve `npm` docs

### PR DESCRIPTION
**Pull request by erbridge**
Make the `npm` script command more general and be more opinionated on package manager.

### CODE REVIEW

**Review by Floppy — APPROVED** [review]

**Comment by Floppy** [comment]
I think standardising on `yarn` is probably the right thing, but you're certainly right in that that wasn't the right place for the idea. We should probably only mention one or the other, given the idea here is to reduce analysis paralysis.

**Review by Floppy — CHANGES_REQUESTED** [review]
Dump yarn for now.

**Comment by erbridge** [comment]
I think `yarn` vs `npm` is a whole conversation (`yarn` released a `v2` that I remember having some concerns about, but haven't checked recently)

**Comment by Floppy** [comment]
> I think `yarn` vs `npm` is a whole conversation 

Exactly. Probably for an ADR rather than here.

**Review by Floppy — APPROVED** [review]

**Pull request merged**
